### ISSUE TITLE
yo team syntax error

### ISSUE THREAD

**Issue by xdaDaveShaw** [DarqueWarrior/generator-team#1]
This is my first attempt so it might be me.

NPM Version 4.1.2
yo Version 1.8.5
generator-team Version 0.1.3

When running `yo team` from a PowerShell window I get the following error message:

```plain
~\Source\Repos> yo team
C:\Users\Dave\AppData\Roaming\npm\node_modules\generator-team\generators\app\index.js:48
   let cmdLnInput = this;
   ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.defineProperty.get [as team:app] (C:\Users\Dave\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:40:23)
    at Store.get (C:\Users\Dave\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:64:35)
    at Environment.get (C:\Users\Dave\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:262:16)
```

**Comment by xdaDaveShaw** [comment]
Ignore me, figured it out.

I fixed it by updating [NodeJS](https://nodejs.org/en/) from some old 4.4.* version to 6.9.4 LTS.
