### ISSUE TITLE
windows server 2016 generator-team 

### ISSUE THREAD

**Issue by Bluear** [DarqueWarrior/generator-team#25]
while using yo team to build a demo project.

C:\Users\tfsadmin>yo team

     _-----_     ╭──────────────────────────╮
    |       |    │     Welcome to DevOps    │
    |--(o)--|    │   powered by Microsoft   │
   `---------´   │       version 0.4.5      │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? Enter VSTS account name
  ({account}.visualstudio.com)
  Or full TFS URL including collection
  (http://tfs:8080/tfs/DefaultCollection)
  Or name of a stored Profile? http://*****:********@139.217.***.***/DefaultCollection
? What is your TFS Personal Access Token? [hidden]
  Getting Agent Queues...
? What agent queue would you like to use? Default
? What type of application do you want to create? .NET Core
? What is the name of your application? YoTeamDemoApp
? Where would you like to deploy? Azure App Service
? What is your Azure subscription name? Visual Studio Enterprise - MPN
? What is your Azure subscription ID? 1dc8df9f-9d86-4633-8cfe-*******
? What is your Azure Tenant ID? 314999a7-b7c5-4b6a-96ea-********
? What is your Service Principal ID? 988086db-5b0e-42b7-b635-********
? What is your Service Principal Key? [hidden]
? Install dependencies? No
+ Found Team project
+ Cloning repository http://*****:********@139.217.***.***/DefaultCollection/_git/YoTeamDemoApp
warning: You appear to have cloned an empty repository.
+ Found Azure Service Endpoint 'Visual Studio Enterprise - MPN'
[?25hC:\Program Files\nodejs\node_global\node_modules\generator-team\generators\app\utility.js:668
         callback(null, obj.value[0].id);
                                     ^

TypeError: Cannot read property 'id' of undefined
    at Request._callback (C:\Program Files\nodejs\node_global\node_modules\generator-team\generators\app\utility.js:668:38)
    at Request.self.callback (C:\Program Files\nodejs\node_global\node_modules\generator-team\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Program Files\nodejs\node_global\node_modules\generator-team\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_global\node_modules\generator-team\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

**Comment by Bluear** [comment]
I've tried many times

**Comment by DarqueWarrior** [comment]
Sorry just seeing this. I will test in the morning.

**Comment by Bluear** [comment]
I solved this  problem by reinstalling the agent , the agent name is "myAgent", did not change. so strange
